### ISSUE TITLE
Degloy to Gh pages

### ISSUE THREAD

**Issue by Juramester** [Uni-Sopron/temalabor-o21-Cosmo-Alkalmazasfejlesztes-Microsoft-Power-Platformon#1]
`/` könyvtárban van az index.html

**Comment by hegyhati** [comment]
beallitottam, de nekem egyelore nem mukodik. neha kell neki kis ido. Ha reggel Neked sem megy, akkor majdnyisd ujra ki az issue-t.

**Comment by hegyhati** [comment]
Na, befrissult, ok.
